
services:

  mysql:
    image: mysql
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8_bin' --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_bin --lower-case-table-names=2 --max-connections=500
    container_name: training_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
     - "3306:3306"

volumes:
  training_mysql_data: